### ISSUE TITLE
responsive styling of prev/next button in text display react strangely

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#24] opened 2015-11-19 13:02 UTC
resize with of browser to see the icons jump vertically.

**Comment by joewiz** [comment] 2015-11-20 19:09
Good point. 

Here's a view of the width just before the problem emerges:

> <img width="671" alt="screen shot 2015-11-20 at 2 02 39 pm" src="https://cloud.githubusercontent.com/assets/59118/11309021/6578f35a-8f8f-11e5-9701-c130a1a75d95.png">

Here's what it looks like when the problem emerges:

> <img width="735" alt="screen shot 2015-11-20 at 2 01 27 pm" src="https://cloud.githubusercontent.com/assets/59118/11309009/51a73634-8f8f-11e5-8168-b2e044cb3754.png">

And at narrowest width, the buttons appear left-aligned:

> <img width="393" alt="screen shot 2015-11-20 at 2 06 49 pm" src="https://cloud.githubusercontent.com/assets/59118/11309137/13b12c80-8f90-11e5-9e54-84dd42182bae.png">

I wonder if these prev/next buttons should be placed at the top and bottom of each page?  This would give us back some width currently occupied by the full-height columns.  It might also solve the responsive problem.  I'm not sure if doing this would have some other bad side effects, so I'm open to your ideas.

**Comment by wolfgangmm** [comment] 2015-11-20 19:15
Note that a swipe left/right will also work on a mobile device, so maybe we could just hide the buttons if the screen width gets below the threshold.

**Comment by joewiz** [comment] 2015-12-10 20:09
While it didn't explicitly mention this issue, I believe that @wolfgangmm's commit https://github.com/eXistSolutions/hsg-shell/commit/f2663f7a60f99388b89652ab0543b0bde67412e3 was intended to address some of these issues:

> - Re-enable broken swipe events for flipping pages on mobile devices.
> - Fix navigation button position on screens < 768px.

But I am still seeing strange artifacts. For example, narrowing the window of Chrome (desktop/Mac) to a certain width in the same browser, the prev/next nav buttons appear inside the text (this is from http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01/d9):

> ![screen_shot_2015-12-10_at_2_19_39_pm](https://cloud.githubusercontent.com/assets/59118/11725733/3175de50-9f49-11e5-8d05-9a45d88e3e69.png)

Similarly, narrowing the width to its minimum shows the next button appearing inside the text (screenshot taken from http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01/d6):

> ![screen_shot_2015-12-10_at_2_14_36_pm](https://cloud.githubusercontent.com/assets/59118/11725606/8d17ee70-9f48-11e5-858b-9068329fedcf.png)

I assume that at these sizes, the prev/next nav buttons are supposed to be tucked up with the `<div class="navigation-top">` alongside the `<h5>` that contains the page title, but since these nav buttons aren't appearing there, the `<h5>` is awkwardly narrow:

> ![screen_shot_2015-12-10_at_2_22_55_pm](https://cloud.githubusercontent.com/assets/59118/11725870/e00edbec-9f49-11e5-86fe-7312f3eb091a.png)

In future fixes on this issue, please attach screenshots revealing how these same views look with the fix.

**Comment by JoernT** [comment] 2015-12-21 14:07
just pushed a version which tries to address the issue. Positioning on very small and very large devices is not optimal - on small devices the arrows will overlap the text and on very large screens the arrows will be relatively far 'outside'.

A better solution would use the grid and place the arrow in its own column but this pure CSS solution might still be aceptable before a larger re-design.

At least this solution will always work and icons won't jump around.

**Comment by wolfgangmm** [comment] 2015-12-22 14:52
Note: the "next" button now often disappears behind the right-hand sidebar boxes, e.g. on

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v01p1/d5

@JoernT yes, swipe left/right should work, at least it did after I fixed it a week ago.

**Comment by JoernT** [comment] 2015-12-23 14:25
ok, will have a look - should be easy to fix

**Comment by wolfgangmm** [comment] 2016-01-03 09:31
This should be fixed by the grid changes described in #67. On small screens, the main navigation buttons are hidden and replaced by buttons next to the document title. Swipe left/right should work as well.

**Closed by wolfgangmm** 2016-01-03 09:31 UTC
Labels: bug, high priority
